services:
  neo4j:
    image: neo4j:2025.12.1
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474" # HTTP (Neo4j Browser)
      - "7687:7687" # Bolt
    volumes:
      - neo4j_data:/data
      - ./import:/var/lib/neo4j/import
    environment:
      NEO4J_AUTH: neo4j/secure_password

volumes:
  neo4j_data:
